# -*- coding: utf-8 -*-
"""udemy_proj

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aufFayaBeSwvhi6HuDjG4nMRVvkHWjYh
"""

import pandas as pd
# Load the dataset
udemy = pd.read_csv("/content/udemy.csv")

udemy.head(300)

for col in udemy.columns:
    print(f"Unique values in column '{col}':")
    print(udemy[col].unique())
    print()

udemy.describe()

import matplotlib.pyplot as plt
import seaborn as sns

# Set the style of seaborn
sns.set(style="whitegrid")

# Distribution of course ratings
plt.figure(figsize=(10, 6))
sns.histplot(udemy['avg_rating'], bins=30, kde=True, color='skyblue')
plt.title('Distribution of Course Ratings on Udemy')
plt.xlabel('Average Rating')
plt.ylabel('Frequency')
plt.show()